# Generated by Django A.I. on 2026-03-28
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):

    dependencies = [
        ("club", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="discipline",
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.SET_NULL, to="club.discipline"),
        ),
    ]
