# Generated by Django 6.0.3 on 2026-03-30 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='is_head_of_discipline',
        ),
        migrations.AlterField(
            model_name='coach',
            name='head_of_discipline',
            field=models.ForeignKey(blank=True, help_text='Discipline this coach is head of (if any, leave empty if not a head coach)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.discipline'),
        ),
    ]
