# Generated by Django 6.0.3 on 2026-03-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_discipline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='player',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='coach',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='coaches/photos/'),
        ),
        migrations.AddField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='players/photos/'),
        ),
        migrations.AddField(
            model_name='team',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='teams/photos/'),
        ),
    ]
