# Generated by Django 6.0.3 on 2026-03-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_remove_coach_is_head_of_discipline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='head_of_discipline',
        ),
        migrations.AddField(
            model_name='coach',
            name='is_head_of_discipline',
            field=models.BooleanField(default=False, help_text='Is this coach the head of a discipline?'),
        ),
    ]
