# Generated by Django 6.0.3 on 2026-03-30 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_remove_coach_head_of_discipline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='head_coach',
            field=models.ForeignKey(blank=True, help_text='Head coach for this discipline (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplines_headed', to='club.coach'),
        ),
    ]
