# Generated by Django 6.0.3 on 2026-03-28 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_team_discipline'),
        ('club', '0003_remove_coach_photo_url_remove_player_photo_url_and_more'),
    ]

    operations = [
    ]
