# Generated by Django 6.0.3 on 2026-03-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_merge_20260328_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='player',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='team',
            name='photo',
        ),
        migrations.AddField(
            model_name='coach',
            name='photo_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='photo_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='photo_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
