# Generated by Django 6.0.3 on 2026-04-01 13:50
#
# All columns in this migration were already added to the live PostgreSQL DB
# by 0005_recurrence_and_preferences (via ADD COLUMN IF NOT EXISTS).
# We use SeparateDatabaseAndState to update Django's migration state without
# re-running the DDL, which would fail with DuplicateColumn on PostgreSQL.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_recurrence_and_preferences'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # columns already exist — skip DDL
            state_operations=[
                migrations.AddField(
                    model_name='calendarevent',
                    name='is_recurring',
                    field=models.BooleanField(default=False),
                ),
                migrations.AddField(
                    model_name='calendarevent',
                    name='recurrence_end_date',
                    field=models.DateField(blank=True, null=True),
                ),
                migrations.AddField(
                    model_name='calendarevent',
                    name='recurrence_group_id',
                    field=models.UUIDField(blank=True, db_index=True, null=True),
                ),
                migrations.AddField(
                    model_name='calendarevent',
                    name='recurrence_interval',
                    field=models.PositiveIntegerField(blank=True, default=1, null=True),
                ),
                migrations.AddField(
                    model_name='calendarevent',
                    name='recurrence_rule',
                    field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10, null=True),
                ),
                migrations.AddField(
                    model_name='pushsubscription',
                    name='discipline_ids',
                    field=models.TextField(default='[]', help_text='JSON array of discipline IDs the subscriber wants notifications for'),
                ),
                migrations.AddField(
                    model_name='pushsubscription',
                    name='team_ids',
                    field=models.TextField(default='[]', help_text='JSON array of team IDs the subscriber wants notifications for'),
                ),
            ],
        ),
    ]
