# Generated by Django 6.0.3 on 2026-03-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_remove_coach_photo_remove_player_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coach',
            name='role',
        ),
        migrations.RemoveField(
            model_name='team',
            name='age_group',
        ),
        migrations.RemoveField(
            model_name='team',
            name='season',
        ),
        migrations.AddField(
            model_name='coach',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='discipline',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discipline',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discipline',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='position_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='year',
            field=models.PositiveIntegerField(blank=True, help_text='Year of birth for age group (e.g. 2016 for U10 in 2026)', null=True),
        ),
    ]
