# Generated by Django 6.0.3 on 2026-03-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_remove_coach_role_remove_team_age_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='is_head_of_discipline',
            field=models.BooleanField(default=False, help_text='Is this coach the head of a discipline?'),
        ),
    ]
