# Generated by Django 6.0.3 on 2026-04-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0008_tournament_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentmatch',
            options={'ordering': ['match_order']},
        ),
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='date',
        ),
        migrations.AddField(
            model_name='tournament',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
