# Generated by Django 6.0.3 on 2026-04-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0009_tournament_date_move'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='season',
            field=models.CharField(blank=True, help_text='e.g. 2025-2026', max_length=20),
        ),
    ]
