# Generated by ChatGPT - add tournament flags
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('club', '0013_add_ended_after_penalties'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='calculate_place_from_groups',
            field=models.BooleanField(default=False, help_text='If true and tournament has only group stage, compute placement from group ranking'),
        ),
        migrations.AddField(
            model_name='groupteam',
            name='show_group_details',
            field=models.BooleanField(default=True, help_text='Show full group details (played/w/d/l/goals) for this team'),
        ),
        migrations.AddField(
            model_name='tournamentmatch',
            name='visible_on_tournament_page',
            field=models.BooleanField(default=True, help_text='Hide this match from the public tournament page when false'),
        ),
    ]
