# Generated by Django 3.2 on 2026-05-05 00:00
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('club', '0014_add_tournament_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('head_admin', 'Head Admin'), ('coach_admin', 'Coach Admin')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_roles', to=settings.AUTH_USER_MODEL)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='club.discipline')),
            ],
            options={
                'unique_together': {('user', 'discipline')},
            },
        ),
    ]
