# Generated by Django 6.0.3 on 2026-05-05 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0016_userrole_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
