# Generated by Django 6.0.3 on 2026-05-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0020_accountant_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.IntegerField(blank=True, help_text='Year for yearly documents; null for general documents', null=True)),
                ('document_type', models.CharField(choices=[('general', 'General'), ('yearly', 'Yearly')], default='yearly', max_length=10)),
                ('file_url', models.CharField(blank=True, help_text='URL to the PDF document in R2/S3 storage', max_length=500, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order within the group (lower = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Official Document',
                'verbose_name_plural': 'Official Documents',
                'ordering': ['document_type', 'year', 'order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('head_admin', 'Head Admin'), ('coach_admin', 'Coach Admin'), ('accountant_admin', 'Accountant Admin')], max_length=20),
        ),
    ]
