# Generated by Django 3.2 on 2026-05-07
from django.db import migrations, models
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('club', '0022_resource_locations_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcebooking',
            name='is_external',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='resourcebooking',
            name='external_organizer',
            field=models.CharField(max_length=200, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resourcebooking',
            name='recurrence_type',
            field=models.CharField(
                max_length=16,
                choices=[
                    ('daily', 'Daily'),
                    ('weekly', 'Weekly'),
                    ('biweekly', 'Biweekly'),
                    ('monthly', 'Monthly'),
                ],
                blank=True,
                null=True
            ),
        ),
        migrations.AddField(
            model_name='resourcebooking',
            name='recurrence_group',
            field=models.UUIDField(blank=True, null=True, db_index=True),
        ),
    ]
