# Generated by Django 6.0.3 on 2026-05-18 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0025_individual_competition'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualresult',
            name='player',
            field=models.ForeignKey(blank=True, help_text='Registered team player. If set, athlete_name is populated automatically.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='individual_results', to='club.player'),
        ),
    ]
