# Generated by Django 6.0.3 on 2026-05-20 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0028_sport_config_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualrace',
            name='unit',
            field=models.CharField(choices=[('none', 'None'), ('seconds', 'Seconds (s)'), ('centimeters', 'Centimeters (cm)'), ('meters', 'Meters (m)'), ('points', 'Points')], default='none', help_text='Unit for participant results (e.g. seconds, centimeters, meters)', max_length=20),
        ),
        migrations.AddField(
            model_name='individualraceparticipant',
            name='result_value',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Measured result (seconds, centimeters, meters, points, etc.)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='sportracetemplate',
            name='unit',
            field=models.CharField(choices=[('none', 'None'), ('seconds', 'Seconds (s)'), ('centimeters', 'Centimeters (cm)'), ('meters', 'Meters (m)'), ('points', 'Points')], default='none', help_text='Default unit for this race type (e.g. seconds for 50m, centimeters for long jump)', max_length=20),
        ),
    ]
